service: serverless-spa-template # Change this

plugins:
  - serverless-finch

custom:
  stage: ${opt:stage, self:provider.stage}
  client:
    bucketName: my-website-bucket-${self:custom.stage} # Change this
    distributionFolder: build
    errorDocument: index.html
  profiles:
    local: local-1
    dev: aws-dev # Change this
    prod: aws-prod # Change this
  regions:
    local: local-1
    dev: eu-west-1
    prod: eu-west-1
  environment:
    dev:
      UI_DOMAIN: dev.example.com # Change this
      UI_BUCKET_HOST: ${self:custom.client.bucketName}.s3-website-${self:provider.region}.amazonaws.com
      CERTIFICATE_ARN: arn:aws:acm:us-east-1:XXX # Change this
    prod:
      UI_DOMAIN: example.com # Change this
      UI_BUCKET_HOST: ${self:custom.client.bucketName}.s3-website-${self:provider.region}.amazonaws.com
      CERTIFICATE_ARN: arn:aws:acm:us-east-1:XXX # Change this
    
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  profile: ${self:custom.profiles.${self:custom.stage}}
  region: ${self:custom.regions.${self:custom.stage}}
  environment: ${self:custom.environment.${self:custom.stage}}

resources:
  Resources:
    UiDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          Aliases:
            - ${self:provider.environment.UI_DOMAIN}
          Comment: ${self:service} UI (${self:custom.stage})
          CustomErrorResponses:
            - ErrorCode: 404
              ErrorCachingMinTTL: 60
              ResponseCode: 200
              ResponsePagePath: /
          DefaultCacheBehavior:
            AllowedMethods: ["GET", "HEAD", "OPTIONS"]
            CachedMethods: ["GET", "HEAD", "OPTIONS"]
            DefaultTTL: 60
            MaxTTL: 60
            MinTTL: 60
            ForwardedValues:
              Headers: ["Origin"]
              QueryString: false
            TargetOriginId: Custom-ui
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
          ViewerCertificate:
            AcmCertificateArn: ${self:provider.environment.CERTIFICATE_ARN}
            SslSupportMethod: sni-only
          Origins:
            - DomainName: ${self:provider.environment.UI_BUCKET_HOST}
              CustomOriginConfig:
                OriginProtocolPolicy: http-only
              Id: Custom-ui
